sudo: required
services:
  - docker
language: bash
script:
  - export REPO=whatever4711/freenom
  - make all

after_success:
  - docker images
  - make push
  - curl -X POST https://hooks.microbadger.com/images/whatever4711/freenom/1g6Fr-aeT9TY8KM-GcePu-_d614=

notifications:
  email: false
  slack:
    on_success: always
    on_failure: change
    secure: s51H7aw8iR4vPsQhwTEVtdgAas1UerX5Y+Keue4V3eQTw7oMJFyEWMkBOk9d0ZPlYOXCFRc5C2M5Clof1lf5tDKyht9g0WxakYHGcN73PWqfSow8doGei3vYc9NW7Ev8mfq0scstdTcOFEafbUilcvjIdvpiCv6Z0DkCaDP5FTUFlQHwzW9J4gU2CeQ8XmyHpsaDL1ij1u0DgYVXaiXwgubDBX3b4ijrhY9j5bFRuy6OEA1xUuhpi+x2GEQ26uWAzGsm4gBbqWy6MnRtFXcOJQLlPrvgn8WhkO/W4JlPwyI3rlk1Ej+88mx9oytdwvH0gOuwOu1JYtCKWZxHeynAKMm1JkSQS5s4Q2CTqtuQJfqXy02IO3kNub1/v35tPv+VcImDqtegcH4PEXz8+36LYqpVol814EGI8oUT/qVcBJegVOgh+yRx/WRF3u+hDTOFlCO3eUwHBYzhSxusQ6ZzdXbOsN/ugo7lNQdClOYSeijFdABL0Ru++0Zcuj9BU7dBYstxenHLxuGrAca86IqAv+X2bCpPtKvhAEMG7q9zt+6jUNBiaXJiYCPKNV5fEt1QpU7fqDw4JjK70/4XTm60r8+kzvgiFyvoAyIVAvzvpSebwdeAM53NS+S+IIlPJ6+kolHTfJ+r7EEDLnRoDfLwkLrugrFx95SiTa66GxlVbHM=
