sudo: required
services:
  - docker
language: bash
script:
  - export REPO=whatever4711/freenom
  - make all
  - docker images

after_success:
  - docker images
  - make push
  - make clean
  - curl -X POST https://hooks.microbadger.com/images/whatever4711/freenom/1g6Fr-aeT9TY8KM-GcePu-_d614=
