FROM armhf/python:3.6-alpine

ADD . /usr/src/app
WORKDIR /usr/src/app
RUN apk add --update --no-cache tini && \
    pip install --no-cache-dir -r requirements.txt && \
    python setup.py install

ENTRYPOINT ["tini", "--", "fdu"]
CMD ["--help"]
