version: '2'

services:
  freenom:
    image: whatever4711/freenom
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.arm64v8
    volumes:
      - ./freenom.yml:/etc/freenom.yml
    command: ["process", "-c", "-t", "3600", "/etc/freenom.yml"]
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 3600s
#        max_attempts: 5
#        window: 120s
