FROM <IMAGE>
<QEMU>

ENV ARCH=<ARCH> \
    FDU_VERSION="1.0"

ADD . /usr/src/app
WORKDIR /usr/src/app
RUN apk add --update --no-cache tini && \
    pip install --no-cache-dir -r requirements.txt && \
    python setup.py install

ENTRYPOINT ["tini", "--", "fdu"]
CMD ["--help"]

LABEL version=${FDU_VERSION} \
    architecture=${ARCH} \
    maintainer="whatever4711@gmail.com"
